# Generated by Django 5.1.1 on 2024-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('apellido', models.CharField(default='S/A', max_length=45)),
                ('direccion', models.CharField(default='S/D', max_length=200)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('apellido', models.CharField(default='S/A', max_length=45)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
